name: Build Pipeline to Dev

on:          
  push:
    branches: [ develop ]
    paths-ignore:
      - '.github/**'
      - 'badges/*'
      - 'pom.xml'
      - '*.svg'
      - '*.json'
      - '*.md'
  workflow_dispatch:
  
env:
  SOURCECODE_MANAGE_BRANCH: develop
  TARGET_ENV: develop
  GITLAB_REPO: git.g-able.com/ais-esaving/service-a.git
  GITLAB_HOME_PATH: service-a
  POM_VERSION_LINE_NUMBER: 13
  CONTAINER_REPO: gableesaving.azurecr.io/api-demo-service-a
  GITOPS_MANAGE_BRANCH: develop
  GITOPS_MANAGE_HOME_PATH: api-demo-service-a
  
  
jobs:
  generate-version:
    runs-on: ubuntu-latest
    #environment: develop
    
    steps:
      - name: Checkout GitOps Repo
        run: |        
          echo "repository: ${{ secret.GITOPS_REPO }}"
          echo "ref: ${{ env.GITOPS_MANAGE_BRANCH }}"
          echo "token: ${{ secrets.GITHUB_TOKEN }}"
          echo "path: manage_gitops"
          
      
